service: slack-app
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-north-1
  role: arn:aws:iam::254437042972:role/slack
  timeout: 5
  stage: ${opt:stage, 'dev'}
  memorySize: 128
functions:
  dispatcher:
    handler: bot.run
    description: description
    events:
      - sns: MybotTopic
      - http:
          path: "/events"
          method: post 

      